version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Redis55"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-135zhihkdzt7i"
s3_prefix = "Redis55"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=\"redis-51\" LatestAmiId=\"/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2\" ElasticacheInstanceClass=\"cache.t3.small\" EC2KeyName=\"nmmashko-kp-two\""

